services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-studio-many}"
    image: localstack/localstack:latest
    ports:
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4510-4559:4510-4559"
    environment:
      - LOCALSTACK_AUTH_TOKEN=ls-kAMAKARu-TARE-1107-2151-DECeDerac05d
      - SERVICES=s3,iam,sts,glue,athena
      - DEBUG=1
      - PERSISTENCE=1
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"